stages:
  - build_test
  - build_prod
  - test
  - deploy_test
  - deploy_prod

build_test:
  image: maven
  stage: build_test
  artifacts:
    paths:
      - target/*.jar
  script: 
    - mvn clean install -P test
  tags:
    - ugrad
  only:
    - projectsetup

build_prod:
  image: maven
  stage: build_prod
  artifacts:
    paths:
      - target
  script: 
    - mvn clean install -P prod
  tags:
    - ugrad
  only:
    - master

test:
  stage: test
  script: 
    - mvn verify
  artifacts: 
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy_test:
  stage: deploy_test
  image: maven
  tags:
    - ugrad
  only:
    - projectsetup
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -r -o StrictHostKeyChecking=no target/*.jar "${DEPLOY_PROD_USER}@${DEPLOY_PROD_HOST}:${DEPLOY_DIR}/dpl-PROD.jar"

deploy_prod:
  stage: deploy_prod
  image: maven
  tags:
    - ugrad
  only:
    - master
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip target
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip"
