stages:
  - build
  - test
  - deploy

build_test:
  image: maven
  stage: build
  artifacts:
    paths:
      - target
  script: 
    - mvn clean install
  tags:
    - ugrad
  except:
    - release

build_prod:
  image: maven
  stage: build
  artifacts:
    paths:
      - target
  script: 
    - mvn clean install -P prod
  tags:
    - ugrad
  only:
    - release

test:
  stage: test
  script: 
    - mvn verify
  artifacts: 
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy_test:
  stage: deploy
  image: maven
  tags:
    - ugrad
  only:
    - develop
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_TEST_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -r -o StrictHostKeyChecking=no target/*.jar "${DEPLOY_TEST_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/dpl-test.jar"

deploy_prod:
  stage: deploy
  image: maven
  tags:
    - ugrad
  only:
    - release
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -r -o StrictHostKeyChecking=no target/*.jar "${DEPLOY_PROD_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/dpl-prod.jar"