stages:
  - build
  - test
  - deploy

build_test:
  image: maven
  stage: build
  artifacts:
    paths:
      - target
  script: 
    - mvn clean install -P test
  tags:
    - ugrad
  except:
    - release

build_prod:
  image: maven
  stage: build
  artifacts:
    paths:
      - target
  script: 
    - mvn clean install -P prod
  tags:
    - ugrad
  only:
    - release

test:
  stage: test
  script: 
    - mvn verify
  artifacts: 
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy_test:
  stage: deploy
  image: maven
  tags:
    - ugrad
  only:
    - develop
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_TEST_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo ${INPUT_JSON} > input.json
    - mv input.json target
    - echo ${SAMPLE_JSON_1} > SampleJSON1.json
    - mv test1.json target
    - echo ${SAMPLE_JSON_2} > SampleJSON2.json
    - mv test2.json target
    - echo ${SAMPLE_JSON_3} > SampleJSON3.json
    - mv test3.json target
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip target
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_TEST_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}${CI_COMMIT_SHORT_SHA}.zip"

deploy_prod:
  stage: deploy
  image: maven
  tags:
    - ugrad
  only:
    - release
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo ${INPUT_JSON} > input.json
    - mv input.json target
    - echo ${SAMPLE_JSON_1} > SampleJSON1.json
    - mv test1.json target
    - echo ${SAMPLE_JSON_2} > SampleJSON2.json
    - mv test2.json target
    - echo ${SAMPLE_JSON_3} > SampleJSON3.json
    - mv test3.json target
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip target
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_PROD_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}${CI_COMMIT_SHORT_SHA}.zip"