stages:
  - build
  - test
    
build:
  image: maven:3-jdk-11-openj9
  stage: build
  cache:
    paths:
      - .m2/repository
  script: 
    - mvn compile
  tags:
    - ugrad

test:
  stage: test
  script: 
    - mvn verify
  artifacts: 
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - ugrad
