stages:
  - build
  - test
  - deploy_test
    
build:
  image: maven
  stage: build
  cache:
    paths:
      - .m2/repository
  script: 
    - mvn compile
  tags:
    - ugrad

test:
  stage: test
  script: 
    - mvn verify
  artifacts: 
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  tags:
    - ugrad

deploy_test:
  stage: deploy_test
  image: maven
  tags:
    - ugrad
  only:
    - projectsetup
  artifacts:
    paths:
      - target
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    #- ls -lrt
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip *
    - scp -r -o StrictHostKeyChecking=no -i ${DEPLOY_SSH_KEY} ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip"

